title: "Блог логопеда Татьяны Павловны"
description: "Советы по развитию речи у детей — блог логопеда-дефектолога в Санкт-Петербурге."
baseurl: "/"
url: "https://blog.fonolog.ru"
theme: minima
markdown: kramdown
plugins:
  - jekyll-seo-tag
